### ISSUE TITLE
Add support for Go Releaser

### ISSUE THREAD

**Issue by marcellodesales** [lacion/cookiecutter-golang#11]
That would be great to get support from https://goreleaser.com/.

**Comment by lacion** [comment]
sorry for the late response. but that is an absolutely great idea.

**Comment by marcellodesales** [comment]
> sorry for the late response. but that is an absolutely great idea.

LOL Closed without being too great of an idea :)

**Comment by lacion** [comment]
> > sorry for the late response. but that is an absolutely great idea.
> 
> LOL Closed without being too great of an idea :)

I'm just doing some clean up, it's been a while since I actually did anything with this template, so I'm working on a new V2 version of it, this will include a full suite of Github Action  including go releaser drafter and removal of unmainted dependencies in favor of others.
