### ISSUE TITLE
Pip?

### ISSUE THREAD

**Issue by sethgrid** [lacion/cookiecutter-golang#2]
Why use pip? `go get` does an install. Use Go to build Go tools. Cheers.

**Comment by romualdr** [comment]
I think it's just for installing cookiecutter, which looks like a Yeoman-like tool to create boilerplates from templates. The worlflow post-initialization will use regular go tools I guess.

**Comment by ChristianWitts** [comment]
@sethgrid `pip` is purely used to install [cookiecutter](https://github.com/audreyr/cookiecutter) which supports plugins to help you scaffold out new projects easily. Below is what is generated by `cookiecutter`.

```
.
├── Dockerfile
├── Dockerfile.build
├── Makefile
├── README.md
├── config
│   └── config.go
├── glide.yaml
├── log
│   └── log.go
├── main.go
└── version.go

2 directories, 9 files
```

**Comment by lacion** [comment]
@ChristianWitts is 100% correct

using cookiecutter is not that bad, is a very good project templates tool like many other, it just happens to be the one i use. i updated the read to show alternatives to pip so you can install cookiecutter.
