### ISSUE TITLE
Instructions to avoid Cobra and CircleCI ignored?

### ISSUE THREAD

**Issue by redthor** [lacion/cookiecutter-golang#26]
**Describe the bug**
My answers to the prompts:
```sh
use_logrus_logging [y]: n
use_viper_config [y]: 
use_cobra_cmd [y]: n
Select use_ci:
1 - travis
2 - circle
3 - none
Choose from 1, 2, 3 (1, 2, 3) [1]: 3
```
However I still get those packages and directories:
```sh
$ cat go.mod 
module github.com/redthor/symbol-svc

require (
        github.com/sirupsen/logrus v1.4.1
        github.com/spf13/cobra v0.0.3
        github.com/spf13/viper v1.3.2
)

$ ll .circleci/
total 12
drwxrwxr-x 2 douglas douglas 4096 Jun 20 23:32 ./
drwxrwxr-x 6 douglas douglas 4096 Jun 20 23:32 ../
-rw-rw-r-- 1 douglas douglas 1429 Jun 20 23:32 config.yml
```

**To Reproduce**
1. Run cookiecutter https://github.com/lacion/cookiecutter-golang.git
2. Answer as above

**Expected behavior**
I didn't expect to have the packages/directories relating to the options I've avoided.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Golang Version 1.12

Thanks

**Comment by lacion** [comment]
thanks for catching this one up.
